apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-sm
  namespace: {{ template "kyverno.namespace" . }}
  labels: {{ include "kyverno.labels" . | nindent 4 }}
    app: kyverno
spec:
  endpoints:
  - honorLabels: true
    port: metrics-port
    metricRelabelings:
    - action: "labeldrop"
      regex: "(user.*)"
  selector:
    matchLabels: {{ include "kyverno.matchLabels" . | nindent 6 }}
      app: kyverno
  namespaceSelector:
    matchNames:
      - {{ template "kyverno.namespace" . }}
